services:

  postgres:
    build: ./postgres
    container_name: postgres_api

    environment:
      POSTGRES_DB: viagens
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d viagens"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq

    ports:
      - "5673:5672"
      - "15673:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    healthcheck:
      test: ["CMD", "rabbit-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


  api_1:
    build: ./backend
    container_name: fastapi_api_1

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    env_file:
      - ./backend/.env

    expose:
      - "8000"


  api_2:
    build: ./backend
    container_name: fastapi_api_2

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    env_file:
      - ./backend/.env

    expose:
      - "8000"


  consumer_auditoria:
    build: ./consumer_auditoria
    container_name: consumer_auditoria

    depends_on:
      rabbitmq:
        condition: service_healthy


  consumer_notificacao:
    build: ./consumer_notificacao
    container_name: consumer_notificacao

    depends_on:
      rabbitmq:
        condition: service_healthy


  gateway:
    build: ./gateway
    container_name: api_gateway

    depends_on:
      - api_1
      - api_2

    ports:
      - "8080:80"


volumes:
  postgres_data:  